### ISSUE TITLE
obi__organism_linker field assumes abbreviation and common name both exist

### ISSUE THREAD

**Issue by dsenalik** [statonlab/tripal_manage_analyses#107]
I don't have the abbreviation and common_name columns populated for all organisms in my chado.organism table.

The obi__organism_linker tripal field therefore only displays a pair of parentheses, although the link works.

I am providing pull request #108 to use genus and species when these are not present, or call the chado_get_organism_scientific_name() function if it is available to get the full name including infraspecific nomenclature.

**Comment by almasaeed2010** [comment]
Merged. Thanks again for the fix!
