### ISSUE TITLE
Formatting Adjustments

### ISSUE THREAD

**Issue by spficklin** [statonlab/tripal_manage_analyses#27]
1) The formatter for the local__analysis field is using a table to organize the organisms.  But I am only able to add one organism for an analysis.    I added the organism to my summary panel and it formats oddly because the organism is a table inside of a table.  I altered the code to use an unordered list instead, but you might want to adjust how that displays in case folks want to do what I did and add it to a summary.

2)  The 'Organism' title for the field is not captilized by default so I have to manually fix it to make it consistent with other TripalFields.  Not a biggie but it just adds an extra step.

**Comment by bradfordcondon** [comment]
>1.  
Just to clarify, youre suggesting the `organism__linker` formatter should be an unordered list?  Done.

As for allowing multiple organisms/analysis, I definitely think it should be supported although we have no need for it in HWG.  is it just a matter of changing the cardinality?

>2.
  Thanks!  my `fields.info` file was overwriting my properly capitalized 'Organism' label: oops.
