### ISSUE TITLE
collapsible fieldsets require additional theme support

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_manage_analyses#67]
```
 $element[$i] = [
        '#type' => 'fieldset',
        '#title' => $name,
        '#attributes' => [
          'class' => [
            'collapsible',
            'collapsed',
          ],
        ],
        // see: https://www.drupal.org/forum/support/module-development-and-code-questions/2012-02-07/drupal-render-fieldset-element
        '#attached' => ['js' => ['misc/collapse.js', 'misc/form.js']],
      ];
      $element[$i]['drawing'] = [
        '#type' => 'item',
        '#title' => t('Drawing'),
        '#prefix' => '<div id="tripal_manage_expression_featureloc_viewer_' . $i . '">',
        '#suffix' => '</div>',
      ];
```

all of our fieldsets do something like this.

However, it only works on some themes and not others.  How do we make this theme independent?

https://www.drupal.org/docs/7/api/javascript-api/managing-javascript-in-drupal-7

**Comment by bradfordcondon** [comment]
i have this error produced by bootstrap:

```
Uncaught TypeError: $(...).find(...).once is not a function
```

**Comment by bradfordcondon** [comment]
* collapsible fieldsets are only a problem on the entity page.  Form collapsible fieldsets are fine
* I fixed the `Uncaught TypeError: $(...).find(...).once is not a function` error by excuding `bootstrap.js` in the theme `.info` file . `exclude[js][] = 'sites/all/themes/bootstrap/js/bootstrap.js'` . However, the problem persists

This makes me think that for whatever reason, attaching hte collapse.js fix doesnt work with bootstrap.  `        '#attached' => ['js' => ['misc/collapse.js', 'misc/form.js']],`

**Comment by almasaeed2010** [comment]
See PR on tripal_analysis_blast for a quick fix https://github.com/tripal/tripal_analysis_blast/pull/34/files
